server:
  port: 9999
  contextPath: /uaa

spring:

  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: ${USERDB_URL:jdbc:mysql://localhost:3306/userdb}
    username: user
    password: password
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory

  data:
    jpa:
      repositories.enabled: true


security:
  sessions: ALWAYS

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.hantsylabs: DEBUG
  file: app.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

