version: '3.3' # specify docker-compose version

services:

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  consul:
    image: consul
    ports:
      - "8500:8500"
      - "53:53"

  mongodb:
    image: mongo
    volumes:
    - mongodata:/data/db
    ports:
    - "27017:27017"
    command: --smallfiles #--rest
    
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongodata:
  
