spring:
  application:
    name: consul-discovery-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: ${management.server.servlet.context-path}/health
        healthCheckInterval: 15s
        tags: foo=bar, baz
        # By default, the Spring Application Context ID is ${spring.application.name}:comma,separated,profiles:${server.port}
        # instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

        # To disable the Consul Discovery Client you can set spring.cloud.consul.discovery.enabled to false.

        # To disable the service registration you can set spring.cloud.consul.discovery.register to false.
management:
  server:
    servlet:
      context-path: /actuator
  security:
    enabled: false