server:
  port: 8383
spring:
  application:
    name: hystrix-turbine


turbine:
  aggregator:
    clusterConfig: HYSTRIX-CLIENT
  appConfig: hystrix-client
#  instanceUrlSuffix.default: actuator/hystrix.stream
