spring:
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: local-authz
            client-id : client
            client-secret : secret
            client-authentication-method : basic
            authorization-grant-type: authorization_code
            scope : profile
            client-name : Login Client
            redirect-uri-template : "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          local-authz :
            authorization-uri: http://localhost:9999/uaa/oauth/authorize
            token-uri: http://localhost:9999/uaa/oauth/token
            user-info-uri : http://localhost:9999/uaa/resources/userinfo
            user-name-attribute : name