server:
  port: 8001

spring:

  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: ${USERDB_URL:jdbc:mysql://localhost:3306/userdb}
    username: user
    password: password
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory

  data:
    jpa:
      repositories.enabled: true

security:
  sessions: NEVER
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6B4yV0n48uT1YTwDq+ghVDBDk17eoy65+tTBItcPIHnyFnR6mkIILmJ5SAvxzV9Jy/mq0wqh0OEQCo2azPgZXojGQvF2+6Hlc8lvt4X44PpQUC6JA9z8uFpwCWRya8DDUxXpaGFm/5TUuWlZZCmMv6b1+s5AyBk5SBADzZx+knipXJFPO3klmhjRbIN7Vb+yuPku/1rVSoyMzFeZW911x5tjQ4bz10H+KEmSkhtB+nCjo1yLNCfBFFbqjWdhCm9vmwXfPnLGiVgpexbqafMaTnCbFzbXj16p/CumpHOny089IAKM1OpBdX2keI4sYgOa5+IUj0448VJbZekVXpjMXwIDAQAB
          -----END PUBLIC KEY-----
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.hantsylabs: DEBUG
  file: app.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

