server:
  port: 8989
spring:
  application:
    name: hystrix-turbine-stream

management:
  endpoints:
    web.exposure.include: '*'
#applications: hystrix
#turbine:
#  aggregator:
#    clusterConfig: ${applications}
#  appConfig: ${applications}
##  instanceUrlSuffix.default: actuator/hystrix.stream
