server:
  port: 8761

logging:
  level:
    org.springframework.security: DEBUG
  file: app.log

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
